Solve linear system via Reduced Row Echelon Form (RREF) and back substitution:

x+2y+z = 2;   
-x-y+2 = 3;   
2x+3y  = 0   


In [1]:
import sympy as sp
import numpy as np
#  matrix itself: coeffs + right vector with constants are in the same matrix
A = sp.Matrix([
    [1, 2, 1, 2],
    [-1, -1, 2, 3],
    [2, 3, 0, 0]])

#saving triangle matrix (rref)
rref_result, pivot_columns = A.rref()
#prepare for numpy processing
rref_numeric = np.array(rref_result).astype(float)

#separate last column, we have matrix w coeffs and matrix w constants (right side of equation)
B = rref_numeric[:, :-1]
b = rref_numeric[:, -1]

#using numpy function to apply back substitution and to find variables' values
solution = np.linalg.solve(B, b).astype(int)
solution


array([-3,  2,  1])

Solve linear system via Row Echelon Form (REF) and back substitution:

x+2y+z = 2;   
-x-y+2 = 3;   
2x+3y  = 0   


In [2]:
import sympy as sp
import numpy as np
#  matrix itself
A = sp.Matrix([
    [1, 2, 1, 2],
    [-1, -1, 2, 3],
    [2, 3, 0, 0]])

#saving triangle matrix
ref_result = A.echelon_form()
#prepare for numpy processing
ref_numeric = np.array(ref_result).astype(float)

#separate last column, we have matrix w coeffs and matrix w constants (right side of equation)
B = ref_numeric[:, :-1]
b = ref_numeric[:, -1]

#using numpy function to apply back substitution and to find variables' values
solution = np.linalg.solve(B, b).astype(int)
solution



array([-3,  2,  1])

For the following linear system, write its augmented matrix, and then perform Elementary Row Operations to obtain its Reduced Row Echelon Form (RREF)

x+2y+z+a = 7;   
x+2y+2z-a= 12;   
2x+4y+6a = 4   


In [3]:
import sympy as sp
import numpy as np
#  matrix itself
D = sp.Matrix([
    [1, 2, 1, 1, 7],
    [1, 2, 2, -1, 12],
    [2, 4, 0, 6, 4]])

#saving triangle matrix
rref_result, pivot_columns = D.rref()
rref_result


Matrix([
[1, 2, 0,  3, 2],
[0, 0, 1, -2, 5],
[0, 0, 0,  0, 0]])

Operations with matrices:   
A+B,   
A-B,   
B+C,   
B-C   

In [9]:
# Matrices
A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[2, 1, 3],[9, 7, 6]])
C = np.array([[2, 1],[3, 4]])


In [16]:
#A+B
R = A+B
R

array([[ 3,  3,  6],
       [13, 12, 12]])

In [21]:
R = 0
#A-B
R = A-B
R



array([[-1,  1,  0],
       [-5, -2,  0]])

In [34]:
#B-C
def matrix_minus_matrix(B, C):
    R = 0
    if B.shape == C.shape:
        R = B-C
        return R
    else:
        print('I can not calculate, wrong dimensions')

matrix_minus_matrix(B,C)

I can not calculate, wrong dimensions


In [36]:
#B+C
def matrix_plus_matrix(B, C):
    R = 0
    if B.shape == C.shape:
        R = B+C
        return R
    else:
        print('I can not calculate, wrong dimensions')

matrix_plus_matrix(B,C)

I can not calculate, wrong dimensions


For matrices A and B perform:    
(i) `2A`   
(ii) `A + B`   
(iii) `2A - 3B`   
(iv) `(2A)ᵀ - (3B)ᵀ`   
(v) `BA`   


In [37]:
A = np.array([[3, 1, 4],[-2, 0, 1],[1, 2, 2]])
B = np.array([[1, 0, 2],[-3, 1, 1], [2, -4, 1]])

In [45]:
def perform_matrix_operation(A, B, operation):
    """
    Perform matrix operations based on the specified operation code.

    Parameters:
    - A (numpy.ndarray): First matrix.
    - B (numpy.ndarray): Second matrix.
    - operation (int): Operation code (1 to 5).

    Returns:
    - numpy.ndarray or str: Result of the matrix operation.
    """
    match operation:
        case 1:
            return 2 * A
        case 2:
            return A + B
        case 3:
            return 2 * A - 3 * B
        case 4:
            return (2 * A).T - (3 * B).T
        case 5:
            return np.dot(B, A)
        case _:
            return "I can not caclulate, check matrices, probably the problem is in their dimensions"

result_1 = perform_matrix_operation(A, B, 1)
result_2 = perform_matrix_operation(A, B, 2)
result_3 = perform_matrix_operation(A, B, 3)
result_4 = perform_matrix_operation(A, B, 4)
result_5 = perform_matrix_operation(A, B, 5)

# Print the results
print("Result for 2A:")
print(result_1)

print("\nResult for A + B:")
print(result_2)

print("\nResult for 2A - 3B:")
print(result_3)

print("\nResult for (2A)ᵀ - (3B)ᵀ:")
print(result_4)

print("\nResult for BA:")
print(result_5)


Result for 2A:
[[ 6  2  8]
 [-4  0  2]
 [ 2  4  4]]

Result for A + B:
[[ 4  1  6]
 [-5  1  2]
 [ 3 -2  3]]

Result for 2A - 3B:
[[ 3  2  2]
 [ 5 -3 -1]
 [-4 16  1]]

Result for (2A)ᵀ - (3B)ᵀ:
[[ 3  5 -4]
 [ 2 -3 16]
 [ 2 -1  1]]

Result for BA:
[[  5   5   8]
 [-10  -1  -9]
 [ 15   4   6]]
